// <auto-generated />
using System;
using CS_Warehouse.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS_Warehouse.Web.Data.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260817223735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CS_Warehouse.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Office supplies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Safety"
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.InventoryBalance", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("InventoryBalances", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryBalance_QuantityOnHand_NonNegative", "QuantityOnHand >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            LocationId = 1,
                            QuantityOnHand = 7,
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ProductId = 2,
                            LocationId = 1,
                            QuantityOnHand = 45,
                            UpdatedAtUtc = new DateTime(2026, 8, 3, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ProductId = 3,
                            LocationId = 1,
                            QuantityOnHand = 0,
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ProductId = 4,
                            LocationId = 2,
                            QuantityOnHand = 2,
                            UpdatedAtUtc = new DateTime(2026, 8, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MAIN",
                            Name = "Main floor"
                        },
                        new
                        {
                            Id = 2,
                            Code = "OVERFLOW",
                            Name = "Overflow storage"
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("IsArchived", "Name");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_ReorderLevel_NonNegative", "ReorderLevel >= 0");

                            t.HasCheckConstraint("CK_Product_UnitCost_NonNegative", "CAST(UnitCost AS REAL) >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Seven-port USB-C desk hub",
                            IsArchived = false,
                            Name = "USB-C hub",
                            ReorderLevel = 10,
                            Sku = "ELEC-100",
                            UnitCost = 29.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Thermal 4 x 6 inch labels",
                            IsArchived = false,
                            Name = "Shipping label roll",
                            ReorderLevel = 20,
                            Sku = "OFF-210",
                            UnitCost = 8.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Powder-free gloves, box of 100",
                            IsArchived = false,
                            Name = "Nitrile gloves",
                            ReorderLevel = 15,
                            Sku = "SAFE-310",
                            UnitCost = 12.75m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "USB handheld barcode scanner",
                            IsArchived = false,
                            Name = "Barcode scanner",
                            ReorderLevel = 3,
                            Sku = "ELEC-120",
                            UnitCost = 64.99m
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "OccurredAtUtc");

                    b.HasIndex("ProductId", "OccurredAtUtc");

                    b.ToTable("StockMovements", t =>
                        {
                            t.HasCheckConstraint("CK_StockMovement_QuantityChange_NonZero", "QuantityChange <> 0");

                            t.HasCheckConstraint("CK_StockMovement_Quantity_Positive", "Quantity > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationId = 1,
                            Note = "Opening balance",
                            OccurredAtUtc = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Quantity = 7,
                            QuantityChange = 7,
                            Type = "Receive"
                        },
                        new
                        {
                            Id = 2,
                            LocationId = 1,
                            Note = "Opening delivery",
                            OccurredAtUtc = new DateTime(2026, 8, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 50,
                            QuantityChange = 50,
                            Type = "Receive"
                        },
                        new
                        {
                            Id = 3,
                            LocationId = 1,
                            Note = "Packed customer orders",
                            OccurredAtUtc = new DateTime(2026, 8, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 5,
                            QuantityChange = -5,
                            Type = "Issue"
                        },
                        new
                        {
                            Id = 4,
                            LocationId = 2,
                            Note = "Opening balance",
                            OccurredAtUtc = new DateTime(2026, 8, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Quantity = 2,
                            QuantityChange = 2,
                            Type = "Receive"
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.InventoryBalance", b =>
                {
                    b.HasOne("CS_Warehouse.Web.Models.Location", "Location")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CS_Warehouse.Web.Models.Product", "Product")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Product", b =>
                {
                    b.HasOne("CS_Warehouse.Web.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.StockMovement", b =>
                {
                    b.HasOne("CS_Warehouse.Web.Models.Location", "Location")
                        .WithMany("StockMovements")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CS_Warehouse.Web.Models.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Location", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Product", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
