// <auto-generated />
using System;
using CS_Warehouse.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS_Warehouse.Web.Data.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CS_Warehouse.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Office supplies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Safety"
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.InventoryBalance", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("InventoryBalances", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryBalance_QuantityOnHand_NonNegative", "QuantityOnHand >= 0");
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MAIN",
                            Name = "Main floor"
                        },
                        new
                        {
                            Id = 2,
                            Code = "OVERFLOW",
                            Name = "Overflow storage"
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("IsArchived", "Name");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_ReorderLevel_NonNegative", "ReorderLevel >= 0");

                            t.HasCheckConstraint("CK_Product_UnitCost_NonNegative", "CAST(UnitCost AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "OccurredAtUtc");

                    b.HasIndex("ProductId", "OccurredAtUtc");

                    b.ToTable("StockMovements", t =>
                        {
                            t.HasCheckConstraint("CK_StockMovement_QuantityChange_NonZero", "QuantityChange <> 0");

                            t.HasCheckConstraint("CK_StockMovement_Quantity_Positive", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.InventoryBalance", b =>
                {
                    b.HasOne("CS_Warehouse.Web.Models.Location", "Location")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CS_Warehouse.Web.Models.Product", "Product")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Product", b =>
                {
                    b.HasOne("CS_Warehouse.Web.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.StockMovement", b =>
                {
                    b.HasOne("CS_Warehouse.Web.Models.Location", "Location")
                        .WithMany("StockMovements")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CS_Warehouse.Web.Models.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Location", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("CS_Warehouse.Web.Models.Product", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
